export {default as interpolate} from "./src/interpolate";
export {default as interpolateArray} from "./src/interpolateArray";
export {default as interpolateNumber} from "./src/interpolateNumber";
export {default as interpolateObject} from "./src/interpolateObject";
export {default as interpolateRound} from "./src/interpolateRound";
export {default as interpolateString} from "./src/interpolateString";
export {default as interpolateTransform} from "./src/interpolateTransform";
export {default as interpolateZoom} from "./src/interpolateZoom";
export {default as interpolators} from "./src/interpolators";
