export {default as array} from "./src/array";
export {default as number} from "./src/number";
export {default as object} from "./src/object";
export {default as round} from "./src/round";
export {default as string} from "./src/string";
export {default as transform} from "./src/transform";
export {default as values} from "./src/values";
export {default as value} from "./src/value";
export {default as zoom} from "./src/zoom";
export {default as rgb} from "./src/rgb";
export {default as hsl} from "./src/hsl";
export {default as hslLong} from "./src/hslLong";
export {default as lab} from "./src/lab";
export {default as hcl} from "./src/hcl";
export {default as hclLong} from "./src/hclLong";

import cubehelixGamma from "./src/cubehelixGamma";
import cubehelixGammaLong from "./src/cubehelixGammaLong";
export var cubehelix = cubehelixGamma(1);
export var cubehelixLong = cubehelixGammaLong(1);
export {cubehelixGamma, cubehelixGammaLong};
